#!/usr/bin/env python
# coding: utf-8
# %%

# %%


import xml.dom.minidom
import xml.etree.ElementTree as ET
import glob
import re

xod_list = glob.glob('*.xod')
ps = []
for i in range(len(xod_list)):
    ps.append(re.sub('ps','',re.findall('\((.*?)\)', xod_list[i])[-1]))

ps.sort(key=int)
file = open("C:\\Users\\cindy.espadas\\Documents\\"+re.findall('From (.*?)\)', xod_list[0])[0]+")_XYZ.txt", "w")
pre = re.split(r"(\d+)ps", xod_list[0])[0]
pos = re.split(r"(\d+)ps", xod_list[0])[2]

for i in range(len(xod_list)):
    xod_file = pre + ps[i] + "ps" + pos
    tree = ET.parse(xod_file)
    root = tree.getroot()
    Molec = ""
    for atom in root.findall("./AtomisticCollectionTreeRoot/PhysicalSystem/SymmetrySystem/MappingSet/MappingFamily/IdentityMapping/Atom3d[@ForcefieldType='c2=']"):
        Molec = Molec + str(atom.attrib["ID"]).rstrip() + ';' + str(atom.attrib["XYZ"]).rstrip() + ';' + '\n'
    Molec = Molec.replace(",", ";")
    file.write("%s\n" %(ps[i]+';'+'X'+';'+'Y'+';'+'Z'+';'))
    file.write("%s\n" %(Molec))
file.close()
